### ISSUE TITLE
How to use io_context::strand to make queries?

### ISSUE THREAD

**Issue by jacob-hegna** [YandexMail/ozo#302]
Quick question, but it's not obvious from the example code. How to make the requests using a strand derived from an io_context instead of the io_context directly? I have rows that I want inserted in a deterministic order in my db.

I ask because ozo::connection_info seems to interface directly with io_context references to build a connection, so passing a strand directly doesn't work (see: https://github.com/yandex/ozo/blob/master/include/ozo/connection_info.h#L71).

**Comment by thed636** [comment]
Hi Jacob!

Strand is an Executor model, so you should use it in that way. You can specify the executor for your handler via `boost::asio::bind_executor()`. In such a case your handler will be dispatched to it.

Hope that helps.

**Comment by jacob-hegna** [comment]
ah, ok - makes perfect sense!
